### PR TITLE
Create Jobs Table

### PR DESCRIPTION
**Pull request by cyrilcero**
- Create Job model 
- Fix associations
- Added create job callback
- Minor refactor to calculate amount callback

Testing:
List all orders ++ details
image

Update Order (Claim Job)
image

List Artist Jobs:
image

### CODE REVIEW

**Comment by cyrilcero** [comment]
Will add routes first and test the api routes before reopening

**Comment by cyrilcero** [comment]
Reopening the PR

1. Updated Routes
2. Added API testing
3. Added additional details in index and show methods in orders controller to facilitate display of order details
4. Fix callback method create_jobs

**Comment by cyrilcero** [comment]
I've polished the bugs now. 

- fix workforce assoc
- fix create order callback method
- fix job assoc 

Kindly review the PR. Thanks!

**Review by louisedungca — APPROVED** [review]
oh hail master cy

**Pull request merged**
